export const NONE = 0

export const SONIC_AIRDROP_NFT_ADDRESS = ''
export const SONIC_AIRDROP_ORDERBOOK_S_ADDRESS = ''
export const SONIC_AIRDROP_ORDERBOOK_USDC_ADDRESS = ''
export const SONIC_AIRDROP_ORDERBOOK_SCUSD_ADDRESS = ''

export const allOrderbookContracts = [
  SONIC_AIRDROP_ORDERBOOK_S_ADDRESS,
  SONIC_AIRDROP_ORDERBOOK_USDC_ADDRESS,
  SONIC_AIRDROP_ORDERBOOK_SCUSD_ADDRESS,
]

export const SONIC_BLAZE_AIRDROP_NFT_ADDRESS = '0x2bBB80Fe426718506C9C0721A53D746C46Fb6A4b'
export const SONIC_BLAZE_AIRDROP_ORDERBOOK_S_ADDRESS = '0xf4BCCdF787B2F7e96eaBb47fEf3465D7F5a7C31C'
export const SONIC_BLAZE_AIRDROP_ORDERBOOK_USDC_ADDRESS = '0xE77Ecab2D8ecb788867AFD4eA65f042A6F9bA5e7'
export const SONIC_BLAZE_AIRDROP_ORDERBOOK_SCUSD_ADDRESS = '0x897C81099f0B646fF15899d5bFD8bBee330A4142'

export const allOrderbookBlazeContracts = [
  SONIC_BLAZE_AIRDROP_ORDERBOOK_S_ADDRESS,
  SONIC_BLAZE_AIRDROP_ORDERBOOK_USDC_ADDRESS,
  SONIC_BLAZE_AIRDROP_ORDERBOOK_SCUSD_ADDRESS,
]

export const quotes = ['s', 'usdc', 'scusd'] // Same order as the orderbook arrays

export default NONE
